#!/usr/bin/env perl

#use local::lib 'lib';

use Modern::Perl;

use Mojolicious::Lite;

get '/' => sub {

    my $self = shift;
    $self->render('home', layout => 'default');

};

#### Pages...

get '/home' => sub {

    my $self = shift;
    $self->render('home', layout => 'default');

} => 'home';

get '/live' => sub {

    my $self = shift;
    $self->render('live', layout => 'default');

} => 'live';

get '/work' => sub {

    my $self = shift;
    $self->render('work', layout => 'default');

} => 'work';

get '/play' => sub {

    my $self = shift;
    $self->render('play', layout => 'default');

} => 'play';

get '/photos' => sub {

    my $self = shift;
    $self->render('photos', layout => 'default');

} => 'photos';

app->secret('after5detroit');
app->start;
