#!/usr/bin/env perl

use Modern::Perl;
use Mojolicious::Lite;
use Crypt::SaltedHash;
use Try::Tiny;
use DateTime;

use lib 'lib';
use After5::Model;

our $MODEL = After5::Model->connect('dbi:SQLite:after5detroit.db');

### After5 Templates

get '/:after5template' => [after5template => qr/\w*/] => sub {

    my $self = shift;
    $self->{'MODEL'} = $MODEL;

    given ($self->param('after5template')) {

        when (/\w+/) {

            return $self->redirect_to('search_show')
              if $_ eq 'search';

            return $self->redirect_to('cpanel_show')
              if $_ eq 'cpanel';

            try { $self->render($_); } finally { $self->render('home'); }
        }

        default {
            $self->render('home');
        }
    }

} => 'after5template';

### After5 Search

any '/search/show' => sub {

    my $self = shift;
    $self->{'MODEL'} = $MODEL;

    return $self->render('search');

} => 'search_show';

### After5 Control Panel

get '/cpanel/show' => sub {

    my $self = shift;
    $self->{'MODEL'} = $MODEL;

    return $self->render('cpanel');

} => 'cpanel_show';

any '/cpanel/settings' => sub {

    my $self = shift;

    try {

        $MODEL->resultset('Settings')
          ->update({admin => $self->param('admin')});

        if (    ($self->param('password_1') ne '')
            and ($self->param('password_1') eq $self->param('password_2')))
        {

            my $crypt = Crypt::SaltedHash->new(algorithm => 'SHA-256');
            $crypt->add($self->param('password_1'));

            my $password = $crypt->generate;

            $MODEL->resultset('Settings')->update({password => $password});
        }

        $MODEL->resultset('Settings')
          ->update({about => $self->param('about')});
    }

    finally {

        $self->redirect_to('cpanel_show');
    }

} => 'cpanel_settings';

any '/cpanel/content' => sub {

    my $self = shift;

    try {

        $MODEL->resultset('Content')->create(

            {   type     => $self->param('type'),
                tags     => $self->param('tags'),
                cities   => $self->param('cities'),
                title    => $self->param('title'),
                body     => $self->param('body'),
                datetime => DateTime->now,
            }
        );
    }

    finally {

        $self->redirect_to('cpanel_show');
    }

} => 'cpanel_content';

any '/cpanel/content/remove' => sub {

    my $self = shift;

    try {

        $MODEL->resultset('Content')->delete({ id => "$self->param('id')" });

    }

    finally {

        $self->redirect_to('cpanel_show');
    }

};

any '/cpanel/ads' => sub {

    my $self = shift;
    return $self->redirect_to('cpanel_show');

} => 'cpanel_ads';

any '/cpanel/login' => sub {

    my $self = shift;

    try {

        my @settings =
          $MODEL->resultset('Settings')
          ->search({admin => $self->param('admin')});

        for (@settings) {

            if (Crypt::SaltedHash->validate(
                    $_->password, $self->param('password')
                )
              )
            {

                $self->session(admin => $_->admin);
                $self->redirect_to('cpanel_show');
            }
        }
    }

    finally {

        $self->redirect_to('cpanel_show');
    }

} => 'cpanel_login';

any '/cpanel/logout' => sub {

    my $self = shift;

    $self->session(expires => 1)
      and return $self->redirect_to('after5template');

} => 'cpanel_logout';

app->secret('after5detroit.com');
app->start;
