=pod

=encoding utf8

=head1 NAME

After5Detroit

=head1 SYNOPSIS

	./after5detroit daemon

=head1 DESCRIPTION

The source code for after5detroit.com

=head2 CPAN Modules

	Modern::Perl Mojolicious::Lite DBIx::Class::Candy SQL::Translator 
	DateTime::Format::SQLite DateTime::Format::ISO8601 Crypt::SaltedHash 
	Try::Tiny HTML::FormatText REST::Google::Search

=head1 BUGS

	http://github.com/thoughtpivot/after5detroit.com/issues

=head1 SEE ALSO

	http://github.com/thoughtpivot/after5detroit.com/wiki

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
