=pod

=encoding utf8

=head1 NAME

After5

=head1 SYNOPSIS

    scripts/after5detroit daemon

=head1 DESCRIPTION

The code behind after5detroit.com

=head2 CPAN Modules

Modern::Perl Mojolicious::Lite Task::Plack DBIx::Class::Candy SQL::Translator 
DateTime::Format::SQLite DateTime::Format::ISO8601 Crypt::SaltedHash 
Try::Tiny HTML::FormatText REST::Google::Search Net::Google::FederatedLogin

=head2 TinyMCE

After5 requires the JavaScript TinyMCE application for its editor.
Please download and extract v3.4.9 into public/tinymce.

=head1 BUGS

http://github.com/thoughtpivot/after5/issues

=head1 SEE ALSO

http://github.com/thoughtpivot/after5/wiki

=head1 COPYRIGHT

After5 v2.0 (c) 2011-2012 After5 Detroit, LLC. 777 Woodward Ave. Detroit, MI. 48226

=cut
