#!/usr/bin/env perl

use Modern::Perl;
use DateTime;

use lib 'lib';
use After5::Model;

our $MODEL = After5::Model->connect("dbi:SQLite:after5detroit.db");
$MODEL->create_ddl_dir('SQLite', '', 'etc/');

system 'sqlite3 after5detroit.db < etc/After5-Model-2.0.1-SQLite.sql';

### Configure Default Settings...

$MODEL->resultset('Settings')->create(

    {   admin           => 'admin',
        password        => 'admin123',
        about           => 'Something about After 5.',
        create_datetime => DateTime->now,
    }
);
